"""
Daily premarket summary persistence — per-ticker rows only.

One table:

    daily_summary_row
      id                SERIAL PK
      run_date          DATE                   -- date of the snapshot
      created_at        TIMESTAMPTZ DEFAULT NOW()
      side              TEXT                   -- "up" or "down"
      rank              INT                    -- 1..5 within the side
      symbol            TEXT
      change            REAL                   -- % change at scan time, signed
      rvol              REAL                   -- relative volume at scan time
      catalyst_strength INT                    -- 1-10 blended catalyst rating
      reason            TEXT                   -- few-words "why is it moving"
      headline          TEXT                   -- headline the reason came from
      news_url          TEXT                   -- link to that headline
      UNIQUE (run_date, side, rank)

Rerunning for an existing run_date is destructive: all rows for that date are
deleted first so we never end up with stale rows mixed in with new ones.

Schema migration: the previous shape was a two-table layout
(daily_summary_run + daily_summary_row joined by run_id). The migration block
in create_daily_summary_tables drops both legacy tables on startup so the new
single-table shape is the only one that exists. Historical rows from the old
shape are NOT migrated — we just start fresh, since the daily snapshot is
regenerated by rerunning the scan.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Dict, List, Optional

import asyncpg


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

async def create_daily_summary_tables(db_conn: asyncpg.Connection) -> None:
    """Idempotent table + index creation. Called from main.py's lifespan.

    Runs a one-shot migration the first time it sees the legacy two-table
    layout: if the old `daily_summary_run` table exists, drop both legacy
    tables so the new single-table shape can be created clean. After the
    migration runs once, the create-if-not-exists path below is the only
    thing that fires on subsequent boots, so history accumulates safely.
    """
    legacy_present = await db_conn.fetchval(
        "SELECT to_regclass('public.daily_summary_run') IS NOT NULL;"
    )
    if legacy_present:
        # Old shape used FK run_id; drop both legacy tables. CASCADE handles
        # the FK so the row table goes away cleanly with the run table.
        await db_conn.execute("DROP TABLE IF EXISTS daily_summary_row CASCADE;")
        await db_conn.execute("DROP TABLE IF EXISTS daily_summary_run CASCADE;")

    await db_conn.execute(
        """
        CREATE TABLE IF NOT EXISTS daily_summary_row (
            id                SERIAL PRIMARY KEY,
            run_date          DATE NOT NULL,
            created_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            side              TEXT NOT NULL,
            rank              INTEGER NOT NULL,
            symbol            TEXT NOT NULL,
            change            REAL,
            rvol              REAL,
            catalyst_strength INTEGER,
            reason            TEXT NOT NULL DEFAULT '',
            headline          TEXT NOT NULL DEFAULT '',
            news_url          TEXT NOT NULL DEFAULT '',
            UNIQUE (run_date, side, rank)
        );
        """
    )
    # History lookups: by date (latest day's snapshot) and by symbol (replay a
    # ticker's catalyst history over time).
    await db_conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_daily_summary_row_run_date
            ON daily_summary_row(run_date DESC);
        """
    )
    await db_conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_daily_summary_row_symbol_date
            ON daily_summary_row(symbol, run_date DESC);
        """
    )


# ---------------------------------------------------------------------------
# Writes
# ---------------------------------------------------------------------------

async def upsert_daily_summary(
    db_conn: asyncpg.Connection,
    run_date: date,
    rows: List[Dict],
) -> None:
    """
    Replace today's snapshot atomically.

    Each row dict must carry: side ("up"|"down"), rank (int), symbol (str),
    change (float|None), rvol (float|None), catalyst_strength (int|None),
    reason (str), headline (str), news_url (str).
    """
    async with db_conn.transaction():
        # Wipe any existing snapshot for this date so rerunning is idempotent.
        await db_conn.execute(
            "DELETE FROM daily_summary_row WHERE run_date = $1;", run_date
        )
        if rows:
            await db_conn.executemany(
                """
                INSERT INTO daily_summary_row
                    (run_date, side, rank, symbol, change, rvol,
                     catalyst_strength, reason, headline, news_url)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10);
                """,
                [
                    (
                        run_date,
                        r["side"],
                        r["rank"],
                        r["symbol"],
                        r.get("change"),
                        r.get("rvol"),
                        r.get("catalyst_strength"),
                        r.get("reason") or "",
                        r.get("headline") or "",
                        r.get("news_url") or "",
                    )
                    for r in rows
                ],
            )


# ---------------------------------------------------------------------------
# Reads
# ---------------------------------------------------------------------------

def _row_to_dict(r) -> Dict:
    return {
        "run_date": r["run_date"],
        "side": r["side"],
        "rank": r["rank"],
        "symbol": r["symbol"],
        "change": r["change"],
        "rvol": r["rvol"],
        "catalyst_strength": r["catalyst_strength"],
        "reason": r["reason"] or "",
        "headline": r["headline"] or "",
        "news_url": r["news_url"] or "",
    }


async def get_latest_daily_summary(
    db_conn: asyncpg.Connection,
) -> Optional[Dict]:
    """
    Return the most recent snapshot (latest run_date), or None if the table is
    empty. Shape: {run_date, created_at, rows: [...]}.
    """
    latest = await db_conn.fetchrow(
        """
        SELECT run_date, MIN(created_at) AS created_at
        FROM daily_summary_row
        WHERE run_date = (SELECT MAX(run_date) FROM daily_summary_row)
        GROUP BY run_date;
        """
    )
    if not latest:
        return None
    rows = await db_conn.fetch(
        """
        SELECT run_date, side, rank, symbol, change, rvol,
               catalyst_strength, reason, headline, news_url
        FROM daily_summary_row
        WHERE run_date = $1
        ORDER BY
            CASE side WHEN 'up' THEN 0 WHEN 'down' THEN 1 ELSE 2 END,
            rank ASC;
        """,
        latest["run_date"],
    )
    return {
        "run_date": latest["run_date"],
        "created_at": latest["created_at"],
        "rows": [_row_to_dict(r) for r in rows],
    }


async def get_daily_summary_by_date(
    db_conn: asyncpg.Connection,
    run_date: date,
) -> Optional[Dict]:
    """Fetch a specific date's snapshot. Same shape as get_latest_daily_summary."""
    rows = await db_conn.fetch(
        """
        SELECT run_date, created_at, side, rank, symbol, change, rvol,
               catalyst_strength, reason, headline, news_url
        FROM daily_summary_row
        WHERE run_date = $1
        ORDER BY
            CASE side WHEN 'up' THEN 0 WHEN 'down' THEN 1 ELSE 2 END,
            rank ASC;
        """,
        run_date,
    )
    if not rows:
        return None
    return {
        "run_date": run_date,
        "created_at": rows[0]["created_at"],
        "rows": [_row_to_dict(r) for r in rows],
    }


async def get_symbol_history(
    db_conn: asyncpg.Connection,
    symbol: str,
    limit: int = 60,
) -> List[Dict]:
    """
    Every catalyst entry recorded for a given ticker, newest first. Lets you go
    back later and ask "why was AAPL gapping on 2026-04-12?" without having to
    re-run anything. Returns a list of row dicts (each with its own run_date).
    """
    sym = (symbol or "").strip().upper()
    rows = await db_conn.fetch(
        """
        SELECT run_date, side, rank, symbol, change, rvol,
               catalyst_strength, reason, headline, news_url
        FROM daily_summary_row
        WHERE symbol = $1
        ORDER BY run_date DESC, rank ASC
        LIMIT $2;
        """,
        sym,
        limit,
    )
    return [_row_to_dict(r) for r in rows]
